### ISSUE TITLE
Missing component libraries

### ISSUE THREAD

**Issue by NullP01nt** [makestuff/umdkv2-lx9#1]
When opening the schematics in KiCad (version 4.0.6), KiCad subsequently tells me that there are two component libraries not found:
- `kicad-lib`
- `special`

I found `kicad-lib` sitting as one of your other repositories, however, `special` is nowhere to be found.
Where can I find the specific libraries in order to properly view all the hardware designs?

**Comment by makestuff** [comment]
I just tried loading this, and it works for me. I did this:

```
$ mkdir $HOME/kicad
$ cd $HOME/kicad
$ git clone git@github.com:makestuff/kicad-lib.git
Cloning into 'kicad-lib'...
remote: Counting objects: 11, done.
remote: Total 11 (delta 0), reused 0 (delta 0), pack-reused 11
Receiving objects: 100% (11/11), 23.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
$ git clone git@github.com:makestuff/umdkv2-lx9.git
Cloning into 'umdkv2-lx9'...
remote: Counting objects: 26, done.
remote: Total 26 (delta 0), reused 0 (delta 0), pack-reused 26
Receiving objects: 100% (26/26), 56.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (8/8), done.
Checking connectivity... done.
$ dpkg -l kicad
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-==================================================
ii  kicad                  0.20140622+bzr40 amd64            Electronic schematic and PCB design software
$ kicad
```
...then in KiCad I opened `umdkv2.pro`, and from the panel I opened `umdkv2.brd` and `umdkv2.sch`. It does not complain about any "special" library. Looking inside the files though, it seems `umdkv2.pro` and `umdkv2.sch` both refer to a "special" library, but on my system that is provided with KiCad (in `/usr/share/kicad/library/special.dcm` and `/usr/share/kicad/library/special.lib`). Perhaps you just need to reinstall KiCad? I just did `sudo apt-get install kicad` on Debian Jessie to get the installation I have.

**Comment by NullP01nt** [comment]
My KiCad installation is fully functional, however, I have the latest stable release (4.0.6) on my Ubuntu 16.04 system. They did away with the `special` library.

What specifically does the design reference from the `special` library?

**Comment by makestuff** [comment]
No idea, it has been many years since I looked at these designs (I had to
install KiCad again just to check for you that it worked). I suggest
getting an older release and using that; it would then be easier to work
out what's used from special.lib.

**Comment by NullP01nt** [comment]
I just installed `kicad_0.20140622+bzr4027-3` and `kicad-common_0.20140622+bzr4027-3` from the Debian Jessie repositories.

The library files are included in `kicad-common`. After some investigation it seems that nothing was referenced from the `special` component library. It seems that KiCad simply puts that reference in the file to indicate that all of these libraries were available at design time, which might not be all that useful.

This issue can be indefinitely closed, since the newer KiCad tools will open the files with no ill effect.
